### ISSUE TITLE
Implement features natively into FrankerFaceZ repo

### ISSUE THREAD

**Issue by Civrock1** [Tester798/ffzenhancing#1]
Not sure if this is the right place for this, but as mentioned by someone else in the support tab on the Chrome web store of this extension, have you considered submitting your features to be used in FFZ natively rather than it being a separate extension? I know the devs over there welcome new pull requests by other contributors/developers.

> For matters regarding extension development, please join our public [FrankerFaceZ Discord](http://discord.gg/UrAkGhT). Upon joining, please request the Developer role for access to developer specific channels.

https://github.com/FrankerFaceZ
https://github.com/FrankerFaceZ/Add-Ons

This would use less browser resources (similar to what FFZ:AP did), have better compatibility with existing features and also allow yourself as well as other developers to expand on the added functions further. 🙂

**Comment by Tester798** [comment]
Thanks for the suggestion. I saw this request in Chrome web store. Probably this can be done, but I'm not sure if it's worth the effort right now. While Chrome web store still allows to load scripts from other sources I think it's fine as it is now because it's easier to maintain for me. If someone likes particular functionality of this extension he can create pull requests directly to the FFZ (or its extensions) repository to implement same functionality.
I don't think it will be using less resources because now it is not a background extension, just a content script for a page (you can't see it in Chrome's Task Manager).
Hope I answered your questions.
