### ISSUE TITLE
Is checkDroppedFrames a new feature?

### ISSUE THREAD

**Issue by thinkpad4** [Tester798/ffzenhancing#22]
@Tester798 I looked at the code from 6.66 and you added something called checkDroppedFrames and I don't see a option in the settings for that.  Is this something that runs in the background because when I watch twitch my dropped frame counter is always increasing and I never notice a issue.  Is it possible to make this a toggleable setting because I think it keeps pausing the stream and playing it when the dropped frames reaches a certain level in a certain time, if I'm reading the code correctly.  It can even be default on I just would like a option to turn it off please

Thank you very much

**Comment by Tester798** [comment]
Hi @thinkpad4 !

Yes, it's a new feature which you can find here:
![image](https://user-images.githubusercontent.com/8844478/141711040-b5fe5e15-b541-483f-8fb9-17ffc405acfa.png)
under "Player" group. It should be off by default as you can see from this line: https://github.com/Tester798/ffzenhancing/blob/eb28a088d97048503f958a3f2b950f8560d59a7c/ffzenhancing.js#L1339

It was introduced to counter Chrome's bug when after switching to the tab with 1080p60 video, the video itself remains frozen, sometimes for a short time (~1-2 sec), sometimes for a very long time (~4-10 sec), and sometimes it remains frozen forever. It seems like the bug was introduced when Chrome devs implemented selective media track pause feature (when video track stops being decoded if it's on inactive tab while audio track can continue to play). I'm not sure if it's related to the low CPU power available to the Chrome itself, or if it can happen to anyone, but I was able to find bug reports for it from other ppl too:
https://crbug.com/897036
https://crbug.com/752726
https://crbug.com/805532 etc.
So this new feature should be able to detect when video freeze happens after tab switch and can pause/unpause video in such case which unfreezes the video. But sometimes on video pause/unpause it can cause playback skip (or repeat) for a few moments, so I left this feature optional. If you will find a way to unfreeze the video without playback skip (or repeat) please let me know.

As you know twitch itself can do playback skips for a moment while switching from lower (background tab) quality to higher. And small pauses can happen when twitch automatically changes quality from higher to lower when tab is in background, and in rare cases it can even take up to few seconds to restore the playback. So maybe you was seeing this.

Thanks for your question.

**Comment by thinkpad4** [comment]
@Tester798 Oh so checkDroppedFrames is part of Fix Video Freeze?  Ok.  I will admit that I'm on a laptop right now, I'll be back on my main rig tomorrow and I'll try it there and report back just in case.  THere are streams that I watch that have dropped frames but I never see a blip so I'll test then.  

The reason I get dropped frames is because I have hardware acceleration turned off on my chrome because when it's on I get some weird issues with the framerate bouncing all over the place and that causes the video to get like slomo is the best I can explain it.  So I kind of have a damned if you do damned if you don't thing going on, Hardware acceleration on = no dropped frames but crazy framerate, or Hardware acceleration off = steady framerate but dropped frames

**Comment by thinkpad4** [comment]
@Tester798 One more thing, is there a easy way of loading 6.64 or 6.65 to test if there is indeed a issue with 6.67?

**Comment by Tester798** [comment]
Yes. I have kind of similar issue with hardware-accelerated video decode: when it's turned on I'm getting crazy freezes while playing 1080p60 videos, so I have it turned off in flags in Chrome too.
I notice dropped frames too, but it doesn't bother me too much. The most annoying thing is video freeze when I switch back to the background tab after some time (20-30 sec), so I wanted to find some solution to this, but wasn't able to fix it with any flags or Chrome's command line arguments, so I found I can fix it (at least partially) here.

> @Tester798 One more thing, is there a easy way of loading 6.64 or 6.65 to test if there is indeed a issue with 6.67?

I added `dev_server.js` and readme to the repository: now you can run your local web server with it. Just get `ffzenhancing.js` from here https://github.com/Tester798/ffzenhancing/blob/ab93a6f6a3ed16986c3b4f4a045a7967906f1eda/ffzenhancing.js and put it over current version.

**Comment by thinkpad4** [comment]
@Tester798 Ok, i'm back on my main rig and not having any issues even on streams with dropped frames, I guess it was the laptop being unable to keep up.  Also thank you for the dev server thing, I'll need to learn node.js first to use it but thank you for adding it.  Closing this, if anything happens to popup in the future I'll reopen it. 

Thank you VERY much
