### ISSUE TITLE
Auto Reload on Erros #1000 ... #5000 nor working?

### ISSUE THREAD

**Issue by kioshimushi** [Tester798/ffzenhancing#30]
Hi, I've been using this add on for FFZ for a long time but something that I've for as long as I remember, not see working is the Auto Reload on Errors #1000...#5000 option.

Lately, it's seems like script like vaft or or video-swap are having problem and introduce those Error #1000 so I've been encountering them quit a lot lately (about 10 times a day).  (see : https://github.com/pixeltris/TwitchAdSolutions/issues/259) 

Having this option enabled in ffzenhancing doesn't work for me and never did for a long time so I can say for sure what version this bug was introduced for me.

As a workaround, I had to use an other add on named Previews (For TTV & YT) that has this exact same functionality to make it reload when this error occurs.

**Comment by Tester798** [comment]
Hi, thanks for your report. Sometimes this option stops working when twitch changes page layout. I try to fix it when I notice it doesn't work anymore. Also I think it may stop working because of some other extension (vaft or or video-swap).
I checked Previews code, and it seems like it uses mostly similar code to check for #1000...#5000 errors. I tried to test it now by manually triggering error #2000 (by selecting offline mode in dev tools) and it looks like it's working fine: when this option becomes enabled, the player starts reloading automatically.

If you would like to provide additional information then you can wait until the error #xxxx occurs and then post the result you are getting when entering next code in dev tools console:
```for (const el of document.querySelectorAll('.content-overlay-gate')) console.log(el.textContent);```
and
```document.querySelector('div[data-a-target="player-overlay-content-gate"]').innerText```
First piece if from ffzenhancing and second one is from Previews.
Also you can check if you are getting any errors in console related to ffzenhancing when error #xxxx occurs.

**Comment by kioshimushi** [comment]
Hi

Well strangely since the last 48H, I don't encounter those errors #1000 anymore. 

I've also tested to manually triggering error #2000 through dev tools and it's working, but it also work when #1000...#5000 errors option isn't enable, so I don't know if the reload on this specific error is baked in twitch by default, I've made sure to remove Previews to test this, even restarted my browser/PC, I only have vaft and FFZ so I don't really see something else doing the auto reaload than twitch itself.

I've re-enabled #1000...#5000 errors and I'll update you If I encountered the error again with the result of the dev console.

**Comment by kioshimushi** [comment]
OK I had i happen just now, error #1000, and no reload from ffzenhancing even though it's enable, Previews is not installed, here are the result for the first one:

```
for (const el of document.querySelectorAll('.content-overlay-gate')) console.log(el.textContent);
VM180:1 Le téléchargement de la vidéo a été annulé. Veuillez réessayer. (Erreur 1000)Cliquez ici pour recharger le lecteur
undefined
```

and for the second one : 

```
document.querySelector('div[data-a-target="player-overlay-content-gate"]').innerText
'Le téléchargement de la vidéo a été annulé. Veuillez réessayer. (Erreur 1000)\n\nCliquez ici pour recharger le lecteur'
```

**Comment by kioshimushi** [comment]
got it once again with a different "VM" if it could help

```
for (const el of document.querySelectorAll('.content-overlay-gate')) console.log(el.textContent);

VM143:1 Le téléchargement de la vidéo a été annulé. Veuillez réessayer. (Erreur 1000)Cliquez ici pour recharger le lecteur
undefined
```

**Comment by Tester798** [comment]
I was suspecting that some languages doesn't have that `#` sign in front of error numbers, especially because Previews code doesn't have that in its checks. I checked few languages, but for some reason I didn't check French.
I removed that sign from the checks so now the setting should work for the French language errors too.
Thanks a lot for your testing!
